/**
 * The demo library, harvested from RomM's own public demo at
 * https://demo.romm.app — `npm run preview:app` and the published demo only.
 *
 * Every game here is homebrew or freeware, because that is what RomM's demo
 * holds: Cave Story for the Mega Drive, Battle Kid, Beneath a Steel Sky, the
 * AtariAge homebrew. That is the reason this file exists rather than a list of
 * invented titles — a front end for a ROM library is judged on how a real
 * library looks in it, and this is a real one that can be shown in public. The
 * cover art and screenshots in `demo/art/` came from that server with
 * it, re-encoded to WebP at display size; every one belongs to whoever made the
 * game.
 *
 * Generated, and pointless to edit by hand: it is a transcript of what the
 * server returned, trimmed to the fields `RommRom` declares, with the
 * millisecond release dates the API hands back converted to the seconds the
 * type says. Refresh it by harvesting again rather than by patching rows.
 */

import type { RommPlatform, RommRom } from '@shared/types'

/**
 * RomM resource path -> the file standing in for it, relative to the page.
 *
 * The art is *not* imported. `demo/` is the preview build's `publicDir`,
 * so those files are copied beside the page and never enter the module graph —
 * which is what keeps 2.8 MB of demo covers out of the shipped app. An
 * `import.meta.glob` here does not: Vite emits the assets while transforming the
 * module, so they land in the application build even though the branch that
 * imports this file is dropped from it.
 *
 * The rows below carry the paths the real server returned, because that is what
 * a `RommRom` holds and what the screens read. This is the one place the preview
 * swaps in something local, and `bridge.ts` resolves it in `imageUrl` — exactly
 * where the app would otherwise ask the main process for an authenticated URL.
 */
export const ART: Readonly<Record<string, string>> = {
  '/assets/romm/resources/roms/1/30/cover/big.png': './art/30-big.webp',
  '/assets/romm/resources/roms/1/30/cover/small.webp': './art/30-small.webp',
  '/assets/romm/resources/roms/1/30/screenshots/0.jpg': './art/30-shot0.webp',
  '/assets/romm/resources/roms/1/30/screenshots/1.jpg': './art/30-shot1.webp',
  '/assets/romm/resources/roms/1/6/cover/big.png': './art/6-big.webp',
  '/assets/romm/resources/roms/1/6/cover/small.webp': './art/6-small.webp',
  '/assets/romm/resources/roms/1/6/screenshots/0.jpg': './art/6-shot0.webp',
  '/assets/romm/resources/roms/1/6/screenshots/1.jpg': './art/6-shot1.webp',
  '/assets/romm/resources/roms/10/139/cover/big.png': './art/139-big.webp',
  '/assets/romm/resources/roms/10/139/cover/small.webp': './art/139-small.webp',
  '/assets/romm/resources/roms/10/139/screenshots/0.jpg': './art/139-shot0.webp',
  '/assets/romm/resources/roms/10/139/screenshots/1.jpg': './art/139-shot1.webp',
  '/assets/romm/resources/roms/10/144/cover/big.png': './art/144-big.webp',
  '/assets/romm/resources/roms/10/144/cover/small.webp': './art/144-small.webp',
  '/assets/romm/resources/roms/10/144/screenshots/0.jpg': './art/144-shot0.webp',
  '/assets/romm/resources/roms/10/144/screenshots/1.jpg': './art/144-shot1.webp',
  '/assets/romm/resources/roms/11/149/cover/big.png': './art/149-big.webp',
  '/assets/romm/resources/roms/11/149/cover/small.webp': './art/149-small.webp',
  '/assets/romm/resources/roms/11/149/screenshots/0.jpg': './art/149-shot0.webp',
  '/assets/romm/resources/roms/11/149/screenshots/1.jpg': './art/149-shot1.webp',
  '/assets/romm/resources/roms/11/154/cover/big.png': './art/154-big.webp',
  '/assets/romm/resources/roms/11/154/cover/small.webp': './art/154-small.webp',
  '/assets/romm/resources/roms/11/154/screenshots/0.jpg': './art/154-shot0.webp',
  '/assets/romm/resources/roms/11/154/screenshots/1.jpg': './art/154-shot1.webp',
  '/assets/romm/resources/roms/12/162/cover/big.png': './art/162-big.webp',
  '/assets/romm/resources/roms/12/162/cover/small.webp': './art/162-small.webp',
  '/assets/romm/resources/roms/12/162/screenshots/0.jpg': './art/162-shot0.webp',
  '/assets/romm/resources/roms/12/162/screenshots/1.jpg': './art/162-shot1.webp',
  '/assets/romm/resources/roms/12/163/cover/big.png': './art/163-big.webp',
  '/assets/romm/resources/roms/12/163/cover/small.webp': './art/163-small.webp',
  '/assets/romm/resources/roms/12/163/screenshots/0.jpg': './art/163-shot0.webp',
  '/assets/romm/resources/roms/12/163/screenshots/1.jpg': './art/163-shot1.webp',
  '/assets/romm/resources/roms/13/169/cover/big.png': './art/169-big.webp',
  '/assets/romm/resources/roms/13/169/cover/small.webp': './art/169-small.webp',
  '/assets/romm/resources/roms/13/169/screenshots/0.jpg': './art/169-shot0.webp',
  '/assets/romm/resources/roms/13/169/screenshots/1.jpg': './art/169-shot1.webp',
  '/assets/romm/resources/roms/13/175/cover/big.png': './art/175-big.webp',
  '/assets/romm/resources/roms/13/175/cover/small.webp': './art/175-small.webp',
  '/assets/romm/resources/roms/13/175/screenshots/0.jpg': './art/175-shot0.webp',
  '/assets/romm/resources/roms/13/175/screenshots/1.jpg': './art/175-shot1.webp',
  '/assets/romm/resources/roms/14/187/cover/big.png': './art/187-big.webp',
  '/assets/romm/resources/roms/14/187/cover/small.png': './art/187-small.webp',
  '/assets/romm/resources/roms/2/42/cover/big.png': './art/42-big.webp',
  '/assets/romm/resources/roms/2/42/cover/small.webp': './art/42-small.webp',
  '/assets/romm/resources/roms/2/42/screenshots/0.jpg': './art/42-shot0.webp',
  '/assets/romm/resources/roms/2/42/screenshots/1.jpg': './art/42-shot1.webp',
  '/assets/romm/resources/roms/2/45/cover/big.png': './art/45-big.webp',
  '/assets/romm/resources/roms/2/45/cover/small.webp': './art/45-small.webp',
  '/assets/romm/resources/roms/2/45/screenshots/0.jpg': './art/45-shot0.webp',
  '/assets/romm/resources/roms/2/45/screenshots/1.jpg': './art/45-shot1.webp',
  '/assets/romm/resources/roms/3/54/cover/big.png': './art/54-big.webp',
  '/assets/romm/resources/roms/3/54/cover/small.webp': './art/54-small.webp',
  '/assets/romm/resources/roms/3/54/screenshots/0.jpg': './art/54-shot0.webp',
  '/assets/romm/resources/roms/3/54/screenshots/1.jpg': './art/54-shot1.webp',
  '/assets/romm/resources/roms/3/58/cover/big.png': './art/58-big.webp',
  '/assets/romm/resources/roms/3/58/cover/small.webp': './art/58-small.webp',
  '/assets/romm/resources/roms/3/58/screenshots/0.jpg': './art/58-shot0.webp',
  '/assets/romm/resources/roms/3/58/screenshots/1.jpg': './art/58-shot1.webp',
  '/assets/romm/resources/roms/4/62/cover/big.png': './art/62-big.webp',
  '/assets/romm/resources/roms/4/62/cover/small.webp': './art/62-small.webp',
  '/assets/romm/resources/roms/4/62/screenshots/0.jpg': './art/62-shot0.webp',
  '/assets/romm/resources/roms/4/62/screenshots/1.jpg': './art/62-shot1.webp',
  '/assets/romm/resources/roms/4/65/cover/big.png': './art/65-big.webp',
  '/assets/romm/resources/roms/4/65/cover/small.webp': './art/65-small.webp',
  '/assets/romm/resources/roms/4/65/screenshots/0.jpg': './art/65-shot0.webp',
  '/assets/romm/resources/roms/4/65/screenshots/1.jpg': './art/65-shot1.webp',
  '/assets/romm/resources/roms/5/75/cover/big.png': './art/75-big.webp',
  '/assets/romm/resources/roms/5/75/cover/small.webp': './art/75-small.webp',
  '/assets/romm/resources/roms/5/75/screenshots/0.jpg': './art/75-shot0.webp',
  '/assets/romm/resources/roms/5/75/screenshots/1.jpg': './art/75-shot1.webp',
  '/assets/romm/resources/roms/5/77/cover/big.png': './art/77-big.webp',
  '/assets/romm/resources/roms/5/77/cover/small.webp': './art/77-small.webp',
  '/assets/romm/resources/roms/5/77/screenshots/0.jpg': './art/77-shot0.webp',
  '/assets/romm/resources/roms/5/77/screenshots/1.jpg': './art/77-shot1.webp',
  '/assets/romm/resources/roms/6/83/cover/big.png': './art/83-big.webp',
  '/assets/romm/resources/roms/6/83/cover/small.webp': './art/83-small.webp',
  '/assets/romm/resources/roms/6/83/screenshots/0.jpg': './art/83-shot0.webp',
  '/assets/romm/resources/roms/6/83/screenshots/1.jpg': './art/83-shot1.webp',
  '/assets/romm/resources/roms/6/86/cover/big.png': './art/86-big.webp',
  '/assets/romm/resources/roms/6/86/cover/small.webp': './art/86-small.webp',
  '/assets/romm/resources/roms/6/86/screenshots/0.jpg': './art/86-shot0.webp',
  '/assets/romm/resources/roms/6/86/screenshots/1.jpg': './art/86-shot1.webp',
  '/assets/romm/resources/roms/7/95/cover/big.jpg': './art/95-big.webp',
  '/assets/romm/resources/roms/7/95/cover/small.jpg': './art/95-small.webp',
  '/assets/romm/resources/roms/7/95/screenshots/0.jpg': './art/95-shot0.webp',
  '/assets/romm/resources/roms/7/95/screenshots/1.jpg': './art/95-shot1.webp',
  '/assets/romm/resources/roms/7/99/cover/big.png': './art/99-big.webp',
  '/assets/romm/resources/roms/7/99/cover/small.webp': './art/99-small.webp',
  '/assets/romm/resources/roms/7/99/screenshots/0.jpg': './art/99-shot0.webp',
  '/assets/romm/resources/roms/7/99/screenshots/1.jpg': './art/99-shot1.webp',
  '/assets/romm/resources/roms/9/123/cover/big.png': './art/123-big.webp',
  '/assets/romm/resources/roms/9/123/cover/small.webp': './art/123-small.webp',
  '/assets/romm/resources/roms/9/123/screenshots/0.jpg': './art/123-shot0.webp',
  '/assets/romm/resources/roms/9/123/screenshots/1.jpg': './art/123-shot1.webp',
  '/assets/romm/resources/roms/9/137/cover/big.png': './art/137-big.webp',
  '/assets/romm/resources/roms/9/137/cover/small.webp': './art/137-small.webp',
  '/assets/romm/resources/roms/9/137/screenshots/0.jpg': './art/137-shot0.webp',
  '/assets/romm/resources/roms/9/137/screenshots/1.jpg': './art/137-shot1.webp'
}

/** Resolve a RomM resource path to the bundled stand-in, if there is one. */
export function artFor(path: string | null): string | null {
  if (!path) return null
  return ART[path.split('?')[0]] ?? null
}

export const PLATFORMS: RommPlatform[] = [
  {
    id: 1,
    slug: 'atari2600',
    fs_slug: 'atari2600',
    name: 'Atari 2600',
    display_name: 'Atari 2600',
    custom_name: null,
    rom_count: 2,
    fs_size_bytes: 36864,
    url_logo: null,
    missing_from_fs: false
  },
  {
    id: 2,
    slug: 'atari7800',
    fs_slug: 'atari7800',
    name: 'Atari 7800',
    display_name: 'Atari 7800',
    custom_name: null,
    rom_count: 2,
    fs_size_bytes: 65792,
    url_logo: null,
    missing_from_fs: false
  },
  {
    id: 3,
    slug: 'c64',
    fs_slug: 'c64',
    name: 'Commodore C64/128/MAX',
    display_name: 'Commodore C64/128/MAX',
    custom_name: null,
    rom_count: 2,
    fs_size_bytes: 240576,
    url_logo: null,
    missing_from_fs: false
  },
  {
    id: 14,
    slug: 'dos',
    fs_slug: 'dos',
    name: 'DOS',
    display_name: 'DOS',
    custom_name: null,
    rom_count: 1,
    fs_size_bytes: 2082617,
    url_logo: null,
    missing_from_fs: false
  },
  {
    id: 4,
    slug: 'gamegear',
    fs_slug: 'gamegear',
    name: 'Sega Game Gear',
    display_name: 'Sega Game Gear',
    custom_name: null,
    rom_count: 2,
    fs_size_bytes: 196608,
    url_logo: null,
    missing_from_fs: false
  },
  {
    id: 5,
    slug: 'gb',
    fs_slug: 'gb',
    name: 'Game Boy',
    display_name: 'Game Boy',
    custom_name: null,
    rom_count: 2,
    fs_size_bytes: 524288,
    url_logo: null,
    missing_from_fs: false
  },
  {
    id: 6,
    slug: 'gba',
    fs_slug: 'gba',
    name: 'Game Boy Advance',
    display_name: 'Game Boy Advance',
    custom_name: null,
    rom_count: 2,
    fs_size_bytes: 5905192,
    url_logo: null,
    missing_from_fs: false
  },
  {
    id: 7,
    slug: 'gbc',
    fs_slug: 'gbc',
    name: 'Game Boy Color',
    display_name: 'Game Boy Color',
    custom_name: null,
    rom_count: 2,
    fs_size_bytes: 2162688,
    url_logo: null,
    missing_from_fs: false
  },
  {
    id: 13,
    slug: 'genesis',
    fs_slug: 'genesis',
    name: 'Sega Mega Drive/Genesis',
    display_name: 'Sega Mega Drive/Genesis',
    custom_name: null,
    rom_count: 2,
    fs_size_bytes: 7405568,
    url_logo: null,
    missing_from_fs: false
  },
  {
    id: 9,
    slug: 'nes',
    fs_slug: 'nes',
    name: 'Nintendo Entertainment System',
    display_name: 'Nintendo Entertainment System',
    custom_name: null,
    rom_count: 2,
    fs_size_bytes: 786464,
    url_logo: null,
    missing_from_fs: false
  },
  {
    id: 10,
    slug: 'scummvm',
    fs_slug: 'scummvm',
    name: 'ScummVM',
    display_name: 'ScummVM',
    custom_name: null,
    rom_count: 2,
    fs_size_bytes: 75928332,
    url_logo: null,
    missing_from_fs: false
  },
  {
    id: 11,
    slug: 'sms',
    fs_slug: 'sms',
    name: 'Sega Master System/Mark III',
    display_name: 'Sega Master System/Mark III',
    custom_name: null,
    rom_count: 2,
    fs_size_bytes: 917504,
    url_logo: null,
    missing_from_fs: false
  },
  {
    id: 12,
    slug: 'snes',
    fs_slug: 'snes',
    name: 'Super Nintendo Entertainment System',
    display_name: 'Super Nintendo Entertainment System',
    custom_name: null,
    rom_count: 2,
    fs_size_bytes: 1048576,
    url_logo: null,
    missing_from_fs: false
  }
]

export const ROMS: RommRom[] = [
  {
    id: 6,
    name: 'Halo 2600',
    slug: 'halo-2600',
    summary:
      "The year is 2552. Planet Earth still exists, but overpopulation has forced many of her former residents to colonize other worlds. After contact with an outer colony was lost, a battlegroup was sent to investigate and was almost completely destroyed; only one badly damaged ship returned to tell of a seemingly unstoppable alien warship that had effortlessly annihilated their forces.\n\nThis was humankind's first encounter with a group of aliens they eventually came to know as the Covenant, a collective of alien races bent on wiping out humanity. A desperate plan is set in motion: board a Covenant vessel and learn the location of the Covenant home world. But before the mission begins, Covenant forces strike and annihilate the attack force.\n\nThe Covenant are now on Earth's doorstep. One ship escapes and makes a blind jump into deep space, hoping to lead the Covenant away from Earth. The ship crashes on Halo--an artificial ring world that is actually a weapon capable of destroying all life in the galaxy should it fall into the hands of the Covenant.\n\nYou are the Master Chief--all that remains of a classified military project to build a series of genetically enhanced super- soldiers. You are humanity's last and best hope against the Covenant--but you're woefully out-matched, and survival is not guaranteed. Can you battle your way through the massive world that is Halo, defeat the Covenant, and save humanity?",
    platform_id: 1,
    platform_slug: 'atari2600',
    platform_fs_slug: 'atari2600',
    platform_display_name: 'Atari 2600',
    fs_name: 'Halo2600.bin',
    fs_name_no_ext: 'Halo2600',
    fs_name_no_tags: 'Halo2600',
    fs_extension: 'bin',
    fs_path: 'roms/atari2600',
    fs_size_bytes: 4096,
    path_cover_small: '/assets/romm/resources/roms/1/6/cover/small.webp',
    path_cover_large: '/assets/romm/resources/roms/1/6/cover/big.png',
    url_cover: null,
    path_video: null,
    regions: [],
    languages: [],
    tags: [],
    revision: null,
    crc_hash: '3978a823',
    md5_hash: '4afa7f377eae1cafb4265c68f73f2718',
    sha1_hash: '2a9647e27ab27e6cf82b3bf122edf212fa34ae86',
    has_simple_single_file: true,
    has_nested_single_file: false,
    has_multiple_files: false,
    missing_from_fs: false,
    metadatum: {
      genres: ['Adventure', 'Shooter'],
      franchises: ['Halo'],
      companies: ['AtariAge', 'Ed Fries'],
      game_modes: ['Single player'],
      age_ratings: ['GA'],
      player_count: '1',
      first_release_date: 1278547200,
      average_rating: 70.01
    },
    rom_user: {
      id: 6,
      rom_id: 6,
      last_played: null,
      now_playing: false,
      backlogged: false,
      hidden: false,
      rating: 0,
      difficulty: 0,
      completion: 0,
      status: null
    },
    files: [
      {
        id: 703,
        rom_id: 6,
        file_name: 'Halo2600.bin',
        file_path: 'roms/atari2600',
        file_size_bytes: 4096,
        full_path: 'roms/atari2600/Halo2600.bin',
        category: 'game'
      }
    ],
    merged_screenshots: [
      '/assets/romm/resources/roms/1/6/screenshots/0.jpg',
      '/assets/romm/resources/roms/1/6/screenshots/1.jpg'
    ],
    created_at: '2025-11-02T21:57:53+00:00',
    updated_at: '2026-07-05T12:15:55+00:00'
  },
  {
    id: 30,
    name: 'Space Rocks',
    slug: 'space-rocks--1',
    summary:
      "While on a routine Stellar Cartography mission, UESC Rains experienced a malfunction and warped into an asteroid field in an unknown sector of space. Unable to get a bearing to safely warp out, the ship must blast the asteroids into smithereens to prevent imminent destruction. To make matters worse, the local inhabitants are xenophobic and have sent warships and Magna-Mines to eliminate the alien (that's you!) threat.\n\nAs the pilot of your ship you must maneuver instantly, rotating left, right and energizing your thrusters to avoid destruction. A direct hit on an asteroid with your laser cannon breaks it in two. A hit on one of these breaks it into two smaller asteroids, a final hit on a small asteroid destroys it completely. Your ship is equipped with a special defensive option to help you avoid collisions when the action gets intense!\n\nSpace Rocks is an impressive blending of the classic arcade games Asteroids and Asteroids Deluxe, crafted for the Atari 2600 by Darrell Spice, Jr. If you're a fan of either arcade cabinet (or both!), you'll love Space Rocks! While Atari's version of Asteroids for the 2600 was passable at the time of its release, Space Rocks blasts far ahead of this early effort. Taking full advantage of the DPC+ mode in our Melody Board, Space Rocks pushes the Atari 2600 to its limits and offers a wide variety of gameplay options to keep you playing for years to come. The graphics, animations, and sound effects are well above what is typically experienced on the 2600.",
    platform_id: 1,
    platform_slug: 'atari2600',
    platform_fs_slug: 'atari2600',
    platform_display_name: 'Atari 2600',
    fs_name: 'Space Rocks.bin',
    fs_name_no_ext: 'Space Rocks',
    fs_name_no_tags: 'Space Rocks',
    fs_extension: 'bin',
    fs_path: 'roms/atari2600',
    fs_size_bytes: 32768,
    path_cover_small: '/assets/romm/resources/roms/1/30/cover/small.webp',
    path_cover_large: '/assets/romm/resources/roms/1/30/cover/big.png',
    url_cover: null,
    path_video: null,
    regions: [],
    languages: [],
    tags: [],
    revision: null,
    crc_hash: 'dabfa820',
    md5_hash: '03db2942cfbea51633726853c81a7b17',
    sha1_hash: '62018681118aa67664243c10f864d19125c10e0d',
    has_simple_single_file: true,
    has_nested_single_file: false,
    has_multiple_files: false,
    missing_from_fs: false,
    metadatum: {
      genres: ['Arcade'],
      franchises: ['Asteroids'],
      companies: ['AtariAge', 'Darrell Spice'],
      game_modes: ['Single player'],
      age_ratings: ['Not Rated'],
      player_count: '1-2',
      first_release_date: 1388448000,
      average_rating: 70.0
    },
    rom_user: {
      id: 30,
      rom_id: 30,
      last_played: null,
      now_playing: false,
      backlogged: false,
      hidden: false,
      rating: 0,
      difficulty: 0,
      completion: 0,
      status: null
    },
    files: [
      {
        id: 712,
        rom_id: 30,
        file_name: 'Space Rocks.bin',
        file_path: 'roms/atari2600',
        file_size_bytes: 32768,
        full_path: 'roms/atari2600/Space Rocks.bin',
        category: 'game'
      }
    ],
    merged_screenshots: [
      '/assets/romm/resources/roms/1/30/screenshots/0.jpg',
      '/assets/romm/resources/roms/1/30/screenshots/1.jpg'
    ],
    created_at: '2025-11-02T21:58:00+00:00',
    updated_at: '2026-07-05T12:16:08+00:00'
  },
  {
    id: 42,
    name: 'Failsafe',
    slug: null,
    summary:
      "The War Continues...\nAfter the successful elimination of the terrorists and their missile silo complexes, we have heard through various sources that they have relocated, and have doubled their security! Once again you must invade enemy territory and prevent the missile launching aimed at Washington D.C. and stop the terrorists once and for all!\n\nIn FailSafe you must make your way through five different terrains in search of the Depot where you will pick up Fail-Safe clues. One letter in the code, in its correct position, appears in the center of your fuel gauge. The sixth terrain is the most dangerous of all - the missile silo is heavily guarded by all enemies, including a mine field! If you make your way past that, you will have to enter the four-digit hexadecimal code to stop the launch and save the world. Do that, and you will start over in a more difficult environment. Otherwise...\n\nAlong the way you will encounter more accurate jeeps, cruise missiles, stationary shooters, pill boxes, and even the terrorists themselves, hiding behind bunkers! Don't worry though, the U.S. has dropped helpful packages which are unfortunately guarded by these enemies. But once you destroy them, the packages are yours for the taking! They will come in these forms:\n\n(F) Freeze Enemy - these will jam the enemy radar and halt them for a period of time.\n(I) Invincible - your tank will be invulnerable to enemies and their fire, but it only lasts for a few seconds, so be quick!\n(S) Speed - gives your tank a temporary speed boost, making it capable to plow through trees, towns and water like they were open road.\n(D) Distance - your tank will be able to shoot much farther distances than your enemies, for a short period of time.\nWhen these power ups are about to run out of their power, your tank will begin to flash. Make sure you get to safe ground!\n\nFailSafe is an unofficial sequel to Atari's original game Countermeasure for the Atari 5200.",
    platform_id: 2,
    platform_slug: 'atari7800',
    platform_fs_slug: 'atari7800',
    platform_display_name: 'Atari 7800',
    fs_name: 'FailSafe (NTSC) (20100227).a78',
    fs_name_no_ext: 'FailSafe (NTSC) (20100227)',
    fs_name_no_tags: 'FailSafe',
    fs_extension: 'a78',
    fs_path: 'roms/atari7800',
    fs_size_bytes: 49280,
    path_cover_small: '/assets/romm/resources/roms/2/42/cover/small.webp',
    path_cover_large: '/assets/romm/resources/roms/2/42/cover/big.png',
    url_cover: null,
    path_video: null,
    regions: [],
    languages: [],
    tags: ['NTSC', '20100227'],
    revision: null,
    crc_hash: 'ea916960',
    md5_hash: '893e3b20d39e7e2dcb381120f7ee0660',
    sha1_hash: 'b88879e0c6d5b30d2c16906c30e5245a061ca59f',
    has_simple_single_file: true,
    has_nested_single_file: false,
    has_multiple_files: false,
    missing_from_fs: false,
    metadatum: {
      genres: ['Strategy'],
      franchises: [],
      companies: ['AtariAge', 'Robert DeCrescenzo'],
      game_modes: [],
      age_ratings: ['Not Rated'],
      player_count: '1',
      first_release_date: 1267228800,
      average_rating: 63.4
    },
    rom_user: {
      id: 42,
      rom_id: 42,
      last_played: null,
      now_playing: false,
      backlogged: false,
      hidden: false,
      rating: 0,
      difficulty: 0,
      completion: 0,
      status: null
    },
    files: [
      {
        id: 740,
        rom_id: 42,
        file_name: 'FailSafe (NTSC) (20100227).a78',
        file_path: 'roms/atari7800',
        file_size_bytes: 49280,
        full_path: 'roms/atari7800/FailSafe (NTSC) (20100227).a78',
        category: 'game'
      }
    ],
    merged_screenshots: [
      '/assets/romm/resources/roms/2/42/screenshots/0.jpg',
      '/assets/romm/resources/roms/2/42/screenshots/1.jpg'
    ],
    created_at: '2025-11-02T21:58:05+00:00',
    updated_at: '2026-07-05T12:17:10+00:00'
  },
  {
    id: 45,
    name: 'Meteor Shower',
    slug: 'meteor-shower--1',
    summary:
      "Meteors are falling to Earth! Defend Earth's surface by blasting away at the falling rocks... But beware! Alien forces have learned what was happening and are taking advantage of our vulnerability to attack us!\n\nThese are your targets:\n\n    Rocks: A small rock gives you twice as many points as a big one. And small rocks that land unhit cost you twice as many points. When big rocks are hit they usually split in two.\n    Spinners: If a spinner lands, it costs you one laser base. Spinners make audible alarm signals.\n    Dive Bombers: These guided missiles try to home in on your base, and change course as they fall. Dive Bombers make a beeping sound as they attack. They are worth 8 big rocks when hit.\n    Saucers: When your score is over 20,000, Saucers occasionally fly past, dropping bombs on your active base location. You get no points for hit-ting the bombs, but each Saucer hit is worth 10 large rocks. Saucers make a distinctive sound as they fly across. Experienced players will find that at a certain score range, a second Saucer will appear as well.",
    platform_id: 2,
    platform_slug: 'atari7800',
    platform_fs_slug: 'atari7800',
    platform_display_name: 'Atari 7800',
    fs_name: 'Meteor Shower (NTSC) (20120218).a78',
    fs_name_no_ext: 'Meteor Shower (NTSC) (20120218)',
    fs_name_no_tags: 'Meteor Shower',
    fs_extension: 'a78',
    fs_path: 'roms/atari7800',
    fs_size_bytes: 16512,
    path_cover_small: '/assets/romm/resources/roms/2/45/cover/small.webp',
    path_cover_large: '/assets/romm/resources/roms/2/45/cover/big.png',
    url_cover: null,
    path_video: null,
    regions: [],
    languages: [],
    tags: ['NTSC', '20120218'],
    revision: null,
    crc_hash: '2e090e9e',
    md5_hash: '48ebe5d935d5f165ce6a091227eee2ce',
    sha1_hash: '9bcfbb1eaae8181818988627cc27e2b74123a89c',
    has_simple_single_file: true,
    has_nested_single_file: false,
    has_multiple_files: false,
    missing_from_fs: false,
    metadatum: {
      genres: ["Shoot'em Up"],
      franchises: [],
      companies: ['AtariAge'],
      game_modes: [],
      age_ratings: ['Not Rated'],
      player_count: '1-2',
      first_release_date: 1293840000,
      average_rating: 63.0
    },
    rom_user: {
      id: 45,
      rom_id: 45,
      last_played: null,
      now_playing: false,
      backlogged: false,
      hidden: false,
      rating: 0,
      difficulty: 0,
      completion: 0,
      status: null
    },
    files: [
      {
        id: 743,
        rom_id: 45,
        file_name: 'Meteor Shower (NTSC) (20120218).a78',
        file_path: 'roms/atari7800',
        file_size_bytes: 16512,
        full_path: 'roms/atari7800/Meteor Shower (NTSC) (20120218).a78',
        category: 'game'
      }
    ],
    merged_screenshots: [
      '/assets/romm/resources/roms/2/45/screenshots/0.jpg',
      '/assets/romm/resources/roms/2/45/screenshots/1.jpg'
    ],
    created_at: '2025-11-02T21:58:06+00:00',
    updated_at: '2026-07-05T12:17:16+00:00'
  },
  {
    id: 54,
    name: 'Bruce Lee II',
    slug: 'bruce-lee-ii',
    summary:
      "A unofficial sequel to the original Bruce Lee game, originally created on PC then later ported to the C64.\n\nAs Bruce Lee ventures into the depth of Tao-Bao's palace to rescue his captive sister, he is beset by a gang of mercenaries that follow him from room to room, challenging his considerable martial arts skills with their own. En route towards the final confrontation with Tao-Bao himself, the Dragon's path will take him from the palace garden, through underground pools (Bruce can now swim and dive), temples, pagodas and even a brief imprisonment in the dungeons.\n\nAlong the way, passages will have to be opened up by engaging in the familiar pastime of collecting hanging lanterns; devious and dynamic traps make things difficult for our hero, but environmental aids like traveling platforms, poles, vines, conveyor belts, and the idiosyncratic moving tapestries can be deftly exploited to avoid the hazards.",
    platform_id: 3,
    platform_slug: 'c64',
    platform_fs_slug: 'c64',
    platform_display_name: 'Commodore C64/128/MAX',
    fs_name: 'Bruce Lee 2.crt',
    fs_name_no_ext: 'Bruce Lee 2',
    fs_name_no_tags: 'Bruce Lee 2',
    fs_extension: 'crt',
    fs_path: 'roms/c64',
    fs_size_bytes: 65728,
    path_cover_small: '/assets/romm/resources/roms/3/54/cover/small.webp',
    path_cover_large: '/assets/romm/resources/roms/3/54/cover/big.png',
    url_cover: null,
    path_video: null,
    regions: [],
    languages: [],
    tags: [],
    revision: null,
    crc_hash: '90a80750',
    md5_hash: '047ab9dab641453a4232843a989f22fb',
    sha1_hash: 'f1adbb439c108623461a209d63815a679d968613',
    has_simple_single_file: true,
    has_nested_single_file: false,
    has_multiple_files: false,
    missing_from_fs: false,
    metadatum: {
      genres: ['Fighting', 'Platform'],
      franchises: ['Bruce Lee'],
      companies: ['Bruno R. Marcos'],
      game_modes: ['Single player'],
      age_ratings: [],
      player_count: '1',
      first_release_date: 1400025600,
      average_rating: 80.0
    },
    rom_user: {
      id: 54,
      rom_id: 54,
      last_played: null,
      now_playing: false,
      backlogged: false,
      hidden: false,
      rating: 0,
      difficulty: 0,
      completion: 0,
      status: null
    },
    files: [
      {
        id: 750,
        rom_id: 54,
        file_name: 'Bruce Lee 2.crt',
        file_path: 'roms/c64',
        file_size_bytes: 65728,
        full_path: 'roms/c64/Bruce Lee 2.crt',
        category: 'game'
      }
    ],
    merged_screenshots: [
      '/assets/romm/resources/roms/3/54/screenshots/0.jpg',
      '/assets/romm/resources/roms/3/54/screenshots/1.jpg'
    ],
    created_at: '2025-11-02T21:58:08+00:00',
    updated_at: '2026-07-05T12:17:34+00:00'
  },
  {
    id: 58,
    name: 'Time of Silence',
    slug: null,
    summary:
      "Time of Silence casts you as a haunted soul wandering a world ravaged by decay, disease, and memories that refuse to fade. Seen from a top-down perspective, you explore abandoned places, interact with broken people, and uncover fragments of a past you thought was buried. A nightmare has stalked you for 30 years – and the name “Sarah” still lingers like a wound. Controlled via joystick with a context-sensitive action menu, the game wraps you in an atmosphere of quiet despair and relentless mystery. Its music drapes every step in melancholy. This is more than just an adventure – it's a slow, immersive descent into a personal apocalypse.",
    platform_id: 3,
    platform_slug: 'c64',
    platform_fs_slug: 'c64',
    platform_display_name: 'Commodore C64/128/MAX',
    fs_name: 'Time of Silence (v1.0.1).d64',
    fs_name_no_ext: 'Time of Silence (v1.0.1)',
    fs_name_no_tags: 'Time of Silence',
    fs_extension: 'd64',
    fs_path: 'roms/c64',
    fs_size_bytes: 174848,
    path_cover_small: '/assets/romm/resources/roms/3/58/cover/small.webp',
    path_cover_large: '/assets/romm/resources/roms/3/58/cover/big.png',
    url_cover: null,
    path_video: null,
    regions: [],
    languages: [],
    tags: [],
    revision: null,
    crc_hash: '0c0c61a8',
    md5_hash: 'ca379436ee8ec59ae650bc3a48f26527',
    sha1_hash: 'edb231d4bbe728a87859f760848df7f8e4b35175',
    has_simple_single_file: true,
    has_nested_single_file: false,
    has_multiple_files: false,
    missing_from_fs: false,
    metadatum: {
      genres: ['Adventure', 'Adventure / Graphic'],
      franchises: [],
      companies: ['Claus', 'Public Domain'],
      game_modes: [],
      age_ratings: ['Not Rated'],
      player_count: '1',
      first_release_date: 1420070400,
      average_rating: null
    },
    rom_user: {
      id: 58,
      rom_id: 58,
      last_played: null,
      now_playing: false,
      backlogged: false,
      hidden: false,
      rating: 0,
      difficulty: 0,
      completion: 0,
      status: null
    },
    files: [
      {
        id: 751,
        rom_id: 58,
        file_name: 'Time of Silence (v1.0.1).d64',
        file_path: 'roms/c64',
        file_size_bytes: 174848,
        full_path: 'roms/c64/Time of Silence (v1.0.1).d64',
        category: 'game'
      }
    ],
    merged_screenshots: [
      '/assets/romm/resources/roms/3/58/screenshots/0.jpg',
      '/assets/romm/resources/roms/3/58/screenshots/1.jpg'
    ],
    created_at: '2025-11-02T21:58:09+00:00',
    updated_at: '2026-07-05T12:17:37+00:00'
  },
  {
    id: 187,
    name: 'xyWords',
    slug: null,
    summary: 'A free cross-word anagrams puzzle game for MS-DOS inspired by "WordScapes".',
    platform_id: 14,
    platform_slug: 'dos',
    platform_fs_slug: 'dos',
    platform_display_name: 'DOS',
    fs_name: 'xyWords.zip',
    fs_name_no_ext: 'xyWords',
    fs_name_no_tags: 'xyWords',
    fs_extension: 'zip',
    fs_path: 'roms/dos',
    fs_size_bytes: 2082617,
    path_cover_small: '/assets/romm/resources/roms/14/187/cover/small.png',
    path_cover_large: '/assets/romm/resources/roms/14/187/cover/big.png',
    url_cover: null,
    path_video: null,
    regions: [],
    languages: [],
    tags: [],
    revision: null,
    crc_hash: '6cffcb72',
    md5_hash: '4dca8a6f04b3268298f4900ea3cbc82d',
    sha1_hash: 'b522e06458438b91693af40f85d7ea258f123ae5',
    has_simple_single_file: true,
    has_nested_single_file: false,
    has_multiple_files: false,
    missing_from_fs: false,
    metadatum: {
      genres: [],
      franchises: [],
      companies: [],
      game_modes: [],
      age_ratings: [],
      player_count: '1',
      first_release_date: null,
      average_rating: null
    },
    rom_user: {
      id: 187,
      rom_id: 187,
      last_played: null,
      now_playing: false,
      backlogged: false,
      hidden: false,
      rating: 0,
      difficulty: 0,
      completion: 0,
      status: null
    },
    files: [
      {
        id: 758,
        rom_id: 187,
        file_name: 'xyWords.zip',
        file_path: 'roms/dos',
        file_size_bytes: 2082617,
        full_path: 'roms/dos/xyWords.zip',
        category: 'game'
      }
    ],
    merged_screenshots: [],
    created_at: '2026-02-09T14:41:27+00:00',
    updated_at: '2026-07-05T12:59:53+00:00'
  },
  {
    id: 62,
    name: 'Swabby - A Snail Tale',
    slug: 'swabby',
    summary:
      '"Rise from your grave!" With the intent of resurrecting the man/beast centurion once more, the mighty Zeus strikes the abandoned graveyard with a vitalizing beam of magic. Only this time, due to a still unexplained glitch in the Segaverse, the magic misses its intended target, and continues downwards to the deepest of the Sega 8-bit catacombs. Here it strikes Swabby, the mazerunning snail built into some of the earliest Master System consoles.\n\nYou must take control of Swabby as he travels through three challenging rounds of 8-bit craziness. Start on Altered Beast\'s graveyard, and proceed to Sonic\'s Green Zone. Then prepare for the last stage, which is set in the unforgiving streets of Shinobi. Dodge and/or shoot the enemies in each stage, and try yo keep safe while also keeping an eye out for chances to beat the high score. A flying enemy is worth 100 points, a shooter is worth 300 points. You are also awarded bonus points for each of your remaining lives at the end of each round',
    platform_id: 4,
    platform_slug: 'gamegear',
    platform_fs_slug: 'gamegear',
    platform_display_name: 'Sega Game Gear',
    fs_name: 'Swabby-GG-1.11.gg',
    fs_name_no_ext: 'Swabby-GG-1.11',
    fs_name_no_tags: 'Swabby-GG-1.11',
    fs_extension: 'gg',
    fs_path: 'roms/gamegear',
    fs_size_bytes: 131072,
    path_cover_small: '/assets/romm/resources/roms/4/62/cover/small.webp',
    path_cover_large: '/assets/romm/resources/roms/4/62/cover/big.png',
    url_cover: null,
    path_video: null,
    regions: [],
    languages: [],
    tags: [],
    revision: null,
    crc_hash: 'b814ad3d',
    md5_hash: 'db672d52225564b6f520e8a0a4b1a4c7',
    sha1_hash: '64f7350ca2c37c44b679e35f9bfd2766c7259cb9',
    has_simple_single_file: true,
    has_nested_single_file: false,
    has_multiple_files: false,
    missing_from_fs: false,
    metadatum: {
      genres: ['Shooter'],
      franchises: [],
      companies: ['Anders S. Jensen'],
      game_modes: ['Single player'],
      age_ratings: [],
      player_count: '1',
      first_release_date: 1459036800,
      average_rating: null
    },
    rom_user: {
      id: 62,
      rom_id: 62,
      last_played: null,
      now_playing: false,
      backlogged: false,
      hidden: false,
      rating: 0,
      difficulty: 0,
      completion: 0,
      status: null
    },
    files: [
      {
        id: 761,
        rom_id: 62,
        file_name: 'Swabby-GG-1.11.gg',
        file_path: 'roms/gamegear',
        file_size_bytes: 131072,
        full_path: 'roms/gamegear/Swabby-GG-1.11.gg',
        category: 'game'
      }
    ],
    merged_screenshots: [
      '/assets/romm/resources/roms/4/62/screenshots/0.jpg',
      '/assets/romm/resources/roms/4/62/screenshots/1.jpg'
    ],
    created_at: '2025-11-02T21:58:09+00:00',
    updated_at: '2026-07-05T12:18:00+00:00'
  },
  {
    id: 65,
    name: 'Fire Track',
    slug: 'tails-adventure-fire-of-robollion',
    summary:
      'This was an attempt at creating a conversion of the BBC Micro game Fire Track to the Sega Game Gear, rewriting it from scratch in Z80 assembly.\nThe player controls a fighter ship which flies at constant speed and heading over a series of worlds. The player is faced with both airborne enemies (who approach in different attack formations) and ground-based enemies. Destruction of a whole attack wave results in bonus points, and destruction of specific ground targets (such as buildings marked with X) results in bonus points (and an occasional extra life) at the end of each level. Some enemies are indestructible and must be avoided. There are no power-ups, although the rate of fire increases with more challenging levels.',
    platform_id: 4,
    platform_slug: 'gamegear',
    platform_fs_slug: 'gamegear',
    platform_display_name: 'Sega Game Gear',
    fs_name: 'ftrack.gg',
    fs_name_no_ext: 'ftrack',
    fs_name_no_tags: 'ftrack',
    fs_extension: 'gg',
    fs_path: 'roms/gamegear',
    fs_size_bytes: 65536,
    path_cover_small: '/assets/romm/resources/roms/4/65/cover/small.webp',
    path_cover_large: '/assets/romm/resources/roms/4/65/cover/big.png',
    url_cover: null,
    path_video: null,
    regions: [],
    languages: [],
    tags: [],
    revision: null,
    crc_hash: 'd6d0a92b',
    md5_hash: '17fa28fea6102a81aafe7961aff200da',
    sha1_hash: 'da53138fa5dc4e253a1ebba50cf59de285c4719e',
    has_simple_single_file: true,
    has_nested_single_file: false,
    has_multiple_files: false,
    missing_from_fs: false,
    metadatum: {
      genres: ['Platform'],
      franchises: [],
      companies: ['Ben Ryves', 'Ryves, Ben'],
      game_modes: ['Single player'],
      age_ratings: [],
      player_count: '1',
      first_release_date: 1639094400,
      average_rating: null
    },
    rom_user: {
      id: 65,
      rom_id: 65,
      last_played: null,
      now_playing: false,
      backlogged: false,
      hidden: false,
      rating: 0,
      difficulty: 0,
      completion: 0,
      status: null
    },
    files: [
      {
        id: 765,
        rom_id: 65,
        file_name: 'ftrack.gg',
        file_path: 'roms/gamegear',
        file_size_bytes: 65536,
        full_path: 'roms/gamegear/ftrack.gg',
        category: 'game'
      }
    ],
    merged_screenshots: [
      '/assets/romm/resources/roms/4/65/screenshots/0.jpg',
      '/assets/romm/resources/roms/4/65/screenshots/1.jpg'
    ],
    created_at: '2025-11-02T21:58:10+00:00',
    updated_at: '2026-07-05T12:18:06+00:00'
  },
  {
    id: 77,
    name: 'Tobu Tobu Girl',
    slug: 'tobu-tobu-girl',
    summary:
      'Your cat is floating into the atmosphere and you are the only one who can save it. Jump, dash, and flap your arms to maneuver around perilous obstacles racing against the clock to retrieve your pet friend before it is too late! Tobu Tobu Girl is a fun and challenging arcade platformer developed by Tangram Games featuring an original soundtrack by potato-tan.',
    platform_id: 5,
    platform_slug: 'gb',
    platform_fs_slug: 'gb',
    platform_display_name: 'Game Boy',
    fs_name: 'tobu.gb',
    fs_name_no_ext: 'tobu',
    fs_name_no_tags: 'tobu',
    fs_extension: 'gb',
    fs_path: 'roms/gb',
    fs_size_bytes: 262144,
    path_cover_small: '/assets/romm/resources/roms/5/77/cover/small.webp',
    path_cover_large: '/assets/romm/resources/roms/5/77/cover/big.png',
    url_cover: null,
    path_video: null,
    regions: [],
    languages: [],
    tags: [],
    revision: null,
    crc_hash: 'ed12be6c',
    md5_hash: '48ea776eace6f2582b70dc965cf2df1f',
    sha1_hash: '8a8f3c1f21f903ea5a7df8fc8b0a6aa5a602e150',
    has_simple_single_file: true,
    has_nested_single_file: false,
    has_multiple_files: false,
    missing_from_fs: false,
    metadatum: {
      genres: ['Platform'],
      franchises: [],
      companies: ['Tangram Games'],
      game_modes: ['Single player'],
      age_ratings: [],
      player_count: '1',
      first_release_date: 1512259200,
      average_rating: null
    },
    rom_user: {
      id: 77,
      rom_id: 77,
      last_played: null,
      now_playing: false,
      backlogged: false,
      hidden: false,
      rating: 0,
      difficulty: 0,
      completion: 0,
      status: null
    },
    files: [
      {
        id: 775,
        rom_id: 77,
        file_name: 'tobu.gb',
        file_path: 'roms/gb',
        file_size_bytes: 262144,
        full_path: 'roms/gb/tobu.gb',
        category: 'game'
      }
    ],
    merged_screenshots: [
      '/assets/romm/resources/roms/5/77/screenshots/0.jpg',
      '/assets/romm/resources/roms/5/77/screenshots/1.jpg'
    ],
    created_at: '2025-11-02T21:58:11+00:00',
    updated_at: '2026-07-11T08:40:44+00:00'
  },
  {
    id: 75,
    name: 'Dangan',
    slug: 'dangan-gb',
    summary:
      'For decades the Dangan Empire and the Houdan Confederation have been at war. As the front line sees most of the action, small remote outposts like the one found on the planet Eshus are often undermanned and overlooked. The Eshus outpost has in fact only got an old pre-war spacecraft, one inexperienced pilot, and a spirited technician stationed there. The two are going about their daily business when a screen suddenly flashes the message "Red alert! The Houdan Confederation is attacking!" The incoming data states that dreadnoughts have come out of hyperspace near the moon of Eshus. The odds are stacked against them but surrendering the outpost would give the enemy a backdoor into the Dangan systems. There\'s no helping it, the Houdan Confederation must be stopped! Although not brimming with confidence, they ready the spacecraft. Tally the technician offers her support as the pilot takes off.',
    platform_id: 5,
    platform_slug: 'gb',
    platform_fs_slug: 'gb',
    platform_display_name: 'Game Boy',
    fs_name: 'dangan.gb',
    fs_name_no_ext: 'dangan',
    fs_name_no_tags: 'dangan',
    fs_extension: 'gb',
    fs_path: 'roms/gb',
    fs_size_bytes: 262144,
    path_cover_small: '/assets/romm/resources/roms/5/75/cover/small.webp',
    path_cover_large: '/assets/romm/resources/roms/5/75/cover/big.png',
    url_cover: null,
    path_video: null,
    regions: [],
    languages: [],
    tags: [],
    revision: null,
    crc_hash: '5359d6db',
    md5_hash: 'c85e5ba3dad5aa705b96da083cdd1a1c',
    sha1_hash: '10029774046dabec2d8c0533caf94091f6e19071',
    has_simple_single_file: true,
    has_nested_single_file: false,
    has_multiple_files: false,
    missing_from_fs: false,
    metadatum: {
      genres: ['Arcade', 'Shooter'],
      franchises: [],
      companies: ['snorpung'],
      game_modes: [],
      age_ratings: [],
      player_count: '1',
      first_release_date: 1546300800,
      average_rating: null
    },
    rom_user: {
      id: 75,
      rom_id: 75,
      last_played: null,
      now_playing: false,
      backlogged: false,
      hidden: false,
      rating: 0,
      difficulty: 0,
      completion: 0,
      status: null
    },
    files: [
      {
        id: 774,
        rom_id: 75,
        file_name: 'dangan.gb',
        file_path: 'roms/gb',
        file_size_bytes: 262144,
        full_path: 'roms/gb/dangan.gb',
        category: 'game'
      }
    ],
    merged_screenshots: [
      '/assets/romm/resources/roms/5/75/screenshots/0.jpg',
      '/assets/romm/resources/roms/5/75/screenshots/1.jpg'
    ],
    created_at: '2025-11-02T21:58:11+00:00',
    updated_at: '2026-07-11T08:40:44+00:00'
  },
  {
    id: 86,
    name: 'Anguna - Warriors Of Virtue',
    slug: 'anguna-warriors-of-virtue',
    summary:
      'It is a short but exciting action-adventure game, reminiscent of the original Legend of Zelda.\nAnguna includes: 5 dungeons and a large overworld to explore, Multiple weapons and items including: a sword, bow & arrows, bear traps, dynamite, lantern, magic boots, and more, Many hidden rooms, secrets, and powerups, Lots of interesting enemies and boss monsters',
    platform_id: 6,
    platform_slug: 'gba',
    platform_fs_slug: 'gba',
    platform_display_name: 'Game Boy Advance',
    fs_name: 'anguna.gba',
    fs_name_no_ext: 'anguna',
    fs_name_no_tags: 'anguna',
    fs_extension: 'gba',
    fs_path: 'roms/gba',
    fs_size_bytes: 1710888,
    path_cover_small: '/assets/romm/resources/roms/6/86/cover/small.webp',
    path_cover_large: '/assets/romm/resources/roms/6/86/cover/big.png',
    url_cover: null,
    path_video: null,
    regions: [],
    languages: [],
    tags: [],
    revision: null,
    crc_hash: '3346891f',
    md5_hash: '9d3a663de5228414d7e6cda7244c5d91',
    sha1_hash: '270c426705df767a4ad2dc69d039842442f779b2',
    has_simple_single_file: true,
    has_nested_single_file: false,
    has_multiple_files: false,
    missing_from_fs: false,
    metadatum: {
      genres: ['Adventure', 'Role-playing (RPG)'],
      franchises: [],
      companies: ['Bite the Chili Productions', 'Bite the Chili Productions', 'Piko Interactive'],
      game_modes: ['Single player'],
      age_ratings: ['E'],
      player_count: '1',
      first_release_date: 1218240000,
      average_rating: 40.0
    },
    rom_user: {
      id: 86,
      rom_id: 86,
      last_played: null,
      now_playing: false,
      backlogged: false,
      hidden: false,
      rating: 0,
      difficulty: 0,
      completion: 0,
      status: null
    },
    files: [
      {
        id: 785,
        rom_id: 86,
        file_name: 'anguna.gba',
        file_path: 'roms/gba',
        file_size_bytes: 1710888,
        full_path: 'roms/gba/anguna.gba',
        category: 'game'
      }
    ],
    merged_screenshots: [
      '/assets/romm/resources/roms/6/86/screenshots/0.jpg',
      '/assets/romm/resources/roms/6/86/screenshots/1.jpg'
    ],
    created_at: '2025-11-02T21:58:13+00:00',
    updated_at: '2026-07-05T12:18:54+00:00'
  },
  {
    id: 83,
    name: 'Motocross Challenge',
    slug: 'motocross-challenge',
    summary:
      "Motocross Challenge is a 2D side-scrolling motorcycle game combining regular racing and tricks. The game can only be played through an emulator or a GBA flashcard but is not strictly homebrew. It is a game made by a commercial developer, but when the project was cancelled by two publishers, they decided to release the game for free. The game can also be ordered on a cartridge from the developer's website. In 2010 it was followed up with an iPhone/iPad release.\n\nThe tracks remind of Excitebike while the gameplay seems inspired by Motocross Maniacs. The game offers two main modes: Free Ride (choose an unlocked bike and track to practise) and Challenge. The Challenge mode involves a series of events in 3 major categories: Beat the Clock (time-based), Trick Attack (points-based) and World Tour (race against 3 AI opponents). When all courses are finished, the final event, MXC Championship, is unlocked. The events are divided over different trees and completing certain courses unlocks new tracks or one of the 8 available bikes. The bikes have different statistics based on speed, handling, acceleration, height, boost and suspension.\n\nGameplay involves a fair amount of physics. When the bike accelerates, the front wheel leaves the ground and this needs to be compensated by nudging the d-pad. Up and down on the d-pad is used to switch lanes. Many tricks (activated through the L-button) involve balance and constant correcting is needed. Next to accelerating, braking and tricks, there is a button for boost. Only a limited amount is offered, but it constantly regenerates at a slow rate. It is used to gain extra speed, especially before big jumps to gain extra air time. The full amount of boost should never be used or let maxed out, as too little or too much slows the bike down. While in the air, using a combination of the L-button and the d-pad, players can perform tricks such as superman, nac-nac of backflip. By completing Trick Attack events, new tricks can be unlocked.\n\nThere are different types of tracks, set on a beach, an arena, downtown, in the snow, in a forest, in a desert and even a dump. They contain a series of jumps but also areas that slow down the bike, along with obstacles. The game screen shows the current position of the player (in World Tour), the current location on the track along with the finish, the time (remaining time in Beat the Clock), the current lap (in World Tour), the boost meter and the amount of points for a trick, and the remaining trick points needed (in Trick Attack). The game supports passwords to save and restore the player's progress.",
    platform_id: 6,
    platform_slug: 'gba',
    platform_fs_slug: 'gba',
    platform_display_name: 'Game Boy Advance',
    fs_name: 'Motocross Challenge (USA) (Proto).gba',
    fs_name_no_ext: 'Motocross Challenge (USA) (Proto)',
    fs_name_no_tags: 'Motocross Challenge',
    fs_extension: 'gba',
    fs_path: 'roms/gba',
    fs_size_bytes: 4194304,
    path_cover_small: '/assets/romm/resources/roms/6/83/cover/small.webp',
    path_cover_large: '/assets/romm/resources/roms/6/83/cover/big.png',
    url_cover: null,
    path_video: null,
    regions: ['USA'],
    languages: [],
    tags: ['Proto'],
    revision: null,
    crc_hash: 'e5a7de43',
    md5_hash: '8b898cdf54095d09d9be2cfcb43ea040',
    sha1_hash: 'b778b784cca09b381f2948c260355bde0a84bc56',
    has_simple_single_file: true,
    has_nested_single_file: false,
    has_multiple_files: false,
    missing_from_fs: false,
    metadatum: {
      genres: ['Platform', 'Racing', 'Sport'],
      franchises: [],
      companies: ['DHG games', 'DHG games'],
      game_modes: [],
      age_ratings: ['E'],
      player_count: '1',
      first_release_date: 1179446400,
      average_rating: 85.7
    },
    rom_user: {
      id: 83,
      rom_id: 83,
      last_played: null,
      now_playing: false,
      backlogged: false,
      hidden: false,
      rating: 0,
      difficulty: 0,
      completion: 0,
      status: null
    },
    files: [
      {
        id: 781,
        rom_id: 83,
        file_name: 'Motocross Challenge (USA) (Proto).gba',
        file_path: 'roms/gba',
        file_size_bytes: 4194304,
        full_path: 'roms/gba/Motocross Challenge (USA) (Proto).gba',
        category: 'game'
      }
    ],
    merged_screenshots: [
      '/assets/romm/resources/roms/6/83/screenshots/0.jpg',
      '/assets/romm/resources/roms/6/83/screenshots/1.jpg'
    ],
    created_at: '2025-11-02T21:58:13+00:00',
    updated_at: '2026-07-05T12:18:48+00:00'
  },
  {
    id: 99,
    name: 'Infinity',
    slug: 'infinity--3',
    summary:
      'An ancient, nameless evil stirs beneath the earth, twisting the land and its people alike with its corrupting force. Two rival nations careen toward war, as a shadowy figure arms them both with unholy weapons of immense power. And a disgraced knight is called upon to overcome the centuries-old pain that divides these peoples, his own grief, and malevolent forces fanning the flames of hate. This epic tale frames a roleplaying game with a unique tactical battle system, a detailed world with over 50 explorable areas and more than 100 items, and beautiful 8-bit graphics — all to immerse you into the world of Infinity!',
    platform_id: 7,
    platform_slug: 'gbc',
    platform_fs_slug: 'gbc',
    platform_display_name: 'Game Boy Color',
    fs_name: 'infinity.gb',
    fs_name_no_ext: 'infinity',
    fs_name_no_tags: 'infinity',
    fs_extension: 'gb',
    fs_path: 'roms/gbc',
    fs_size_bytes: 2097152,
    path_cover_small: '/assets/romm/resources/roms/7/99/cover/small.webp',
    path_cover_large: '/assets/romm/resources/roms/7/99/cover/big.png',
    url_cover: null,
    path_video: null,
    regions: [],
    languages: [],
    tags: [],
    revision: null,
    crc_hash: '4ade94aa',
    md5_hash: '6d6507bd38c76a9baa90b8e305ebea13',
    sha1_hash: 'fdfd6d4cbebbf64fc7d1264f0450be270be89823',
    has_simple_single_file: true,
    has_nested_single_file: false,
    has_multiple_files: false,
    missing_from_fs: false,
    metadatum: {
      genres: ['Role-playing (RPG)', 'Tactical'],
      franchises: [],
      companies: ['Incube8 Games'],
      game_modes: ['Single player'],
      age_ratings: ['RP'],
      player_count: '1',
      first_release_date: 1769904000,
      average_rating: null
    },
    rom_user: {
      id: 99,
      rom_id: 99,
      last_played: null,
      now_playing: false,
      backlogged: false,
      hidden: false,
      rating: 0,
      difficulty: 0,
      completion: 0,
      status: null
    },
    files: [
      {
        id: 798,
        rom_id: 99,
        file_name: 'infinity.gb',
        file_path: 'roms/gbc',
        file_size_bytes: 2097152,
        full_path: 'roms/gbc/infinity.gb',
        category: 'game'
      }
    ],
    merged_screenshots: [
      '/assets/romm/resources/roms/7/99/screenshots/0.jpg',
      '/assets/romm/resources/roms/7/99/screenshots/1.jpg'
    ],
    created_at: '2025-11-02T21:58:16+00:00',
    updated_at: '2026-07-05T12:19:14+00:00'
  },
  {
    id: 95,
    name: 'GBC Spelunky',
    slug: null,
    summary:
      'GBC-spelunky is an attempt to demake Spelunky 2 for Game Boy Color. This project resulted in a playable version, albeit as an endless runner due to ambitious goals and content cuts. Some rough edges may exist due to rushed development in the final weeks, but the game features a complete character controller, robust entity system, and functional level generation and auto-tiling.',
    platform_id: 7,
    platform_slug: 'gbc',
    platform_fs_slug: 'gbc',
    platform_display_name: 'Game Boy Color',
    fs_name: 'GBCspelunky.gbc',
    fs_name_no_ext: 'GBCspelunky',
    fs_name_no_tags: 'GBCspelunky',
    fs_extension: 'gbc',
    fs_path: 'roms/gbc',
    fs_size_bytes: 65536,
    path_cover_small: '/assets/romm/resources/roms/7/95/cover/small.jpg',
    path_cover_large: '/assets/romm/resources/roms/7/95/cover/big.jpg',
    url_cover: null,
    path_video: null,
    regions: [],
    languages: [],
    tags: [],
    revision: null,
    crc_hash: '2d60d327',
    md5_hash: '920142e65e4b27c61848ed165c739777',
    sha1_hash: '27aca0703c7dada169a019c113899c91ce7b225d',
    has_simple_single_file: true,
    has_nested_single_file: false,
    has_multiple_files: false,
    missing_from_fs: false,
    metadatum: {
      genres: [],
      franchises: ['Spelunky'],
      companies: ['sukus'],
      game_modes: ['Single-player'],
      age_ratings: [],
      player_count: '1',
      first_release_date: null,
      average_rating: null
    },
    rom_user: {
      id: 95,
      rom_id: 95,
      last_played: null,
      now_playing: false,
      backlogged: false,
      hidden: false,
      rating: 0,
      difficulty: 0,
      completion: 0,
      status: null
    },
    files: [
      {
        id: 795,
        rom_id: 95,
        file_name: 'GBCspelunky.gbc',
        file_path: 'roms/gbc',
        file_size_bytes: 65536,
        full_path: 'roms/gbc/GBCspelunky.gbc',
        category: 'game'
      }
    ],
    merged_screenshots: [
      '/assets/romm/resources/roms/7/95/screenshots/0.jpg',
      '/assets/romm/resources/roms/7/95/screenshots/1.jpg'
    ],
    created_at: '2025-11-02T21:58:15+00:00',
    updated_at: '2026-07-05T12:55:10+00:00'
  },
  {
    id: 169,
    name: 'Demons of Asteborg',
    slug: 'demons-of-asteborg',
    summary:
      'Long ago in the Kingdom of Asteborg, a war broke out, pitting humans and demons against each other in a bloody battle. Sagramor, a powerful mercenary, and Maria, a sorceress with fighting magic, joined forces to defeat the demonic army.\n\nSagramor found a way to lock the demons in an alternate dimension, at the cost of his own life. His sacrifice earned him the title of "Legend of Asteborg".\n\nShortly before the end of the war, Maria gave birth to a child named Gareth.\n\nShe died 4 years later.\n\nGareth was then taken in by the royal orphanage, and Bohort, the leader of the armed troops, saw in him an invaluable potential. He trained him from an early age to become a formidable warrior.\n\nDecades later, Zadimus, the former leader of the Demons, who survived the great war, found a way to reopen the portal to the parallel dimension in order to free his fellow Demons and declare war on the humans in order to take back the Kingdom of Asteborg.\n\nAs Gareth, now the royal guard of Asteborg, you will go on an adventure, braving the lands of the kingdom and its dangerous lands populated by bloodthirsty monsters.\n\nAlong the way, you\'ll learn more and more about the ancient war and your identity.\n\nBut beware, Zadimus won\'t let you get away with it...',
    platform_id: 13,
    platform_slug: 'genesis',
    platform_fs_slug: 'genesis',
    platform_display_name: 'Sega Mega Drive/Genesis',
    fs_name: 'Demons_of_Asteborg_DEMO_v21072020.bin',
    fs_name_no_ext: 'Demons_of_Asteborg_DEMO_v21072020',
    fs_name_no_tags: 'Demons_of_Asteborg_DEMO_v21072020',
    fs_extension: 'bin',
    fs_path: 'roms/genesis',
    fs_size_bytes: 3407872,
    path_cover_small: '/assets/romm/resources/roms/13/169/cover/small.webp',
    path_cover_large: '/assets/romm/resources/roms/13/169/cover/big.png',
    url_cover: null,
    path_video: null,
    regions: [],
    languages: [],
    tags: [],
    revision: null,
    crc_hash: '8163415e',
    md5_hash: '94286ef831f89948c9c9219937a4b06d',
    sha1_hash: 'be4b6e1e627fbfdf0c25df7496a053a0289691a9',
    has_simple_single_file: true,
    has_nested_single_file: false,
    has_multiple_files: false,
    missing_from_fs: false,
    metadatum: {
      genres: ['Adventure', 'Arcade', 'Indie', 'Platform'],
      franchises: [],
      companies: ['Neofid Studios'],
      game_modes: ['Single player'],
      age_ratings: ['12', '12', '12', '12+', 'M', 'T'],
      player_count: '1',
      first_release_date: 1627776000,
      average_rating: 85.0
    },
    rom_user: {
      id: 169,
      rom_id: 169,
      last_played: null,
      now_playing: false,
      backlogged: false,
      hidden: false,
      rating: 0,
      difficulty: 0,
      completion: 0,
      status: null
    },
    files: [
      {
        id: 799,
        rom_id: 169,
        file_name: 'Demons_of_Asteborg_DEMO_v21072020.bin',
        file_path: 'roms/genesis',
        file_size_bytes: 3407872,
        full_path: 'roms/genesis/Demons_of_Asteborg_DEMO_v21072020.bin',
        category: 'game'
      }
    ],
    merged_screenshots: [
      '/assets/romm/resources/roms/13/169/screenshots/0.jpg',
      '/assets/romm/resources/roms/13/169/screenshots/1.jpg'
    ],
    created_at: '2025-11-02T22:19:50+00:00',
    updated_at: '2026-07-05T12:19:23+00:00'
  },
  {
    id: 175,
    name: 'Cave Story',
    slug: 'cave-story-md',
    summary:
      'This is a rewrite/port of the popular freeware game Cave Story for Sega MegaDrive/Genesis. The engine is built using SGDK.\n\nCave Story is a metroidvania platformer with the amnesiac soldier Quote finding a city of rabbits called Mimigas. The Mimigas are preyed on by an evil doctor, who kidnaps them for his evil experiments.\n\nThey still remember Arthur, a hero from their past and others are awaiting for the return of Dragons. The soldier soon falls in with Sue, a stranger to the Mimigas, but the only one who seems to know about the Dragon Eggs. Unfortunately the doctor wants her next.\n\nThe game resembles a NES platformer with a fast gameplay. The main character collects weapons (blade, bubbler, fireball, machine gun, nemesis, super missile launcher, polar star, snake and spur) that can be leveled up 3 times.\n\nThere are also health capsules to increase his life bar. There is a variety of jumping puzzles and boss battles to challenge players as they explore the game.',
    platform_id: 13,
    platform_slug: 'genesis',
    platform_fs_slug: 'genesis',
    platform_display_name: 'Sega Mega Drive/Genesis',
    fs_name: 'cavestory.bin',
    fs_name_no_ext: 'cavestory',
    fs_name_no_tags: 'cavestory',
    fs_extension: 'bin',
    fs_path: 'roms/genesis',
    fs_size_bytes: 3997696,
    path_cover_small: '/assets/romm/resources/roms/13/175/cover/small.webp',
    path_cover_large: '/assets/romm/resources/roms/13/175/cover/big.png',
    url_cover: null,
    path_video: null,
    regions: [],
    languages: [],
    tags: [],
    revision: null,
    crc_hash: '416f1c1b',
    md5_hash: 'b5c0862dfdb923dfdb5e4789c76f531a',
    sha1_hash: 'b46bf62243fbe776abc6000c08dc79c1c34b0f3a',
    has_simple_single_file: true,
    has_nested_single_file: false,
    has_multiple_files: false,
    missing_from_fs: false,
    metadatum: {
      genres: ['Adventure', 'Platform'],
      franchises: ['Cave Story'],
      companies: ['andwn'],
      game_modes: ['Single player'],
      age_ratings: [],
      player_count: '1',
      first_release_date: 1552435200,
      average_rating: null
    },
    rom_user: {
      id: 175,
      rom_id: 175,
      last_played: null,
      now_playing: false,
      backlogged: false,
      hidden: false,
      rating: 0,
      difficulty: 0,
      completion: 0,
      status: null
    },
    files: [
      {
        id: 809,
        rom_id: 175,
        file_name: 'cavestory.bin',
        file_path: 'roms/genesis',
        file_size_bytes: 3997696,
        full_path: 'roms/genesis/cavestory.bin',
        category: 'game'
      }
    ],
    merged_screenshots: [
      '/assets/romm/resources/roms/13/175/screenshots/0.jpg',
      '/assets/romm/resources/roms/13/175/screenshots/1.jpg'
    ],
    created_at: '2025-11-02T22:21:01+00:00',
    updated_at: '2026-07-05T12:19:39+00:00'
  },
  {
    id: 137,
    name: 'The Legends of Owlia',
    slug: 'the-legends-of-owlia',
    summary:
      "The Legends of Owlia is Gradual Games' second release for the NES.\nIt is an action-adventure game inspired by StarTropics, Crystalis, and the Legend of Zelda.\n\nOnce upon a time. On a world far beyond imagining. Six great owls brought forth a land called Owlia. Together, they reigned in peace and wisdom for eighty thousand years. However, their pride in the beautiful land and sky of Owlia led them to forget the vast vast seas... Mermon, King of the Mermen, oft rose to the surface to view the Land of Owlia. His desire for sunlight, sky, and green forests grew until he decided the seas were not enough for him. He endeavored to summon the six great owls one by one. He began sapping their powers of flight, empowering his minions to float towards the Land of Owlia to claim it for his own. However, one great owl eluded him.. Silmaran, the White King. Soaring high above the Land of Owlia, as Mermon's forces grew in power, he searched for one who might heed his call to rescue the great owls and restore the Land of Owlia.\nGuide heroine Adlanniel and her owl friend Tyto to free the great owls and defeat Mermon king of the Mermen!!",
    platform_id: 9,
    platform_slug: 'nes',
    platform_fs_slug: 'nes',
    platform_display_name: 'Nintendo Entertainment System',
    fs_name: 'owlia.nes',
    fs_name_no_ext: 'owlia',
    fs_name_no_tags: 'owlia',
    fs_extension: 'nes',
    fs_path: 'roms/nes',
    fs_size_bytes: 524304,
    path_cover_small: '/assets/romm/resources/roms/9/137/cover/small.webp',
    path_cover_large: '/assets/romm/resources/roms/9/137/cover/big.png',
    url_cover: null,
    path_video: null,
    regions: [],
    languages: [],
    tags: [],
    revision: null,
    crc_hash: '26858010',
    md5_hash: '2c853160353de6f1272ac503c2661223',
    sha1_hash: '406f293f6aa8ee93f42e12c4f991d7d593c78b44',
    has_simple_single_file: true,
    has_nested_single_file: false,
    has_multiple_files: false,
    missing_from_fs: false,
    metadatum: {
      genres: ['Adventure', 'Indie', 'Role-playing (RPG)'],
      franchises: ['The Legend of Zelda'],
      companies: ['Gradual Games', 'Gradual Games', 'Infinite Nes Lives'],
      game_modes: ['Single player'],
      age_ratings: [],
      player_count: '1',
      first_release_date: 1359590400,
      average_rating: null
    },
    rom_user: {
      id: 137,
      rom_id: 137,
      last_played: null,
      now_playing: false,
      backlogged: false,
      hidden: false,
      rating: 0,
      difficulty: 0,
      completion: 0,
      status: null
    },
    files: [
      {
        id: 835,
        rom_id: 137,
        file_name: 'owlia.nes',
        file_path: 'roms/nes',
        file_size_bytes: 524304,
        full_path: 'roms/nes/owlia.nes',
        category: 'game'
      }
    ],
    merged_screenshots: [
      '/assets/romm/resources/roms/9/137/screenshots/0.jpg',
      '/assets/romm/resources/roms/9/137/screenshots/1.jpg'
    ],
    created_at: '2025-11-02T21:58:22+00:00',
    updated_at: '2026-07-05T12:21:04+00:00'
  },
  {
    id: 123,
    name: 'Battle Kid: Fortress Of Peril',
    slug: 'battle-kid-2-mountain-of-torment',
    summary:
      'Battle Kid: Fortress Of Peril is a homebrew 2D platform video game, released in February 2010 for the Nintendo Entertainment System, created by American developer Sivak Games, and published through Retrozone with the cover art designed by Larry Bundy Jr. Unlike most games in the modern era, Battle Kid is available for purchase only on a physical NES cartridge. While there has been a demand for a downloadable version, the developer has stated that the game is currently not planned to be released on any other formats due to a contract with Retrozone.',
    platform_id: 9,
    platform_slug: 'nes',
    platform_fs_slug: 'nes',
    platform_display_name: 'Nintendo Entertainment System',
    fs_name: 'Battle Kid 2.nes',
    fs_name_no_ext: 'Battle Kid 2',
    fs_name_no_tags: 'Battle Kid 2',
    fs_extension: 'nes',
    fs_path: 'roms/nes',
    fs_size_bytes: 262160,
    path_cover_small: '/assets/romm/resources/roms/9/123/cover/small.webp',
    path_cover_large: '/assets/romm/resources/roms/9/123/cover/big.png',
    url_cover: null,
    path_video: null,
    regions: [],
    languages: [],
    tags: [],
    revision: null,
    crc_hash: '70cc40a0',
    md5_hash: '37d15ab83697dce281caee7c3ff2f6dd',
    sha1_hash: '5e61c00266bce84018cb1712527129d8c8cbe755',
    has_simple_single_file: true,
    has_nested_single_file: false,
    has_multiple_files: false,
    missing_from_fs: false,
    metadatum: {
      genres: ['Platform'],
      franchises: [],
      companies: ['RetroUSB', 'Sivak Games'],
      game_modes: ['Single player'],
      age_ratings: [],
      player_count: '1',
      first_release_date: 1355529600,
      average_rating: null
    },
    rom_user: {
      id: 123,
      rom_id: 123,
      last_played: null,
      now_playing: false,
      backlogged: false,
      hidden: false,
      rating: 0,
      difficulty: 0,
      completion: 0,
      status: null
    },
    files: [
      {
        id: 819,
        rom_id: 123,
        file_name: 'Battle Kid 2.nes',
        file_path: 'roms/nes',
        file_size_bytes: 262160,
        full_path: 'roms/nes/Battle Kid 2.nes',
        category: 'game'
      }
    ],
    merged_screenshots: [
      '/assets/romm/resources/roms/9/123/screenshots/0.jpg',
      '/assets/romm/resources/roms/9/123/screenshots/1.jpg'
    ],
    created_at: '2025-11-02T21:58:20+00:00',
    updated_at: '2026-07-05T12:20:35+00:00'
  },
  {
    id: 139,
    name: 'Beneath A Steel Sky',
    slug: 'beneath-a-steel-sky',
    summary:
      "Beneath A Steel Sky (BASS) is set in a post-apocalyptic Australia where you're an orphan living with a tribe in the wastelands the 'gap' when a helicopter comes to take you to the enormous Union City. The game starts with the helicopter crashing down in the city and you making your escape into one of the large tall plants. Your goal? To discover who you really are and why you were taken to the city.",
    platform_id: 10,
    platform_slug: 'scummvm',
    platform_fs_slug: 'scummvm',
    platform_display_name: 'ScummVM',
    fs_name: 'Beneath a Steel Sky',
    fs_name_no_ext: 'Beneath a Steel Sky',
    fs_name_no_tags: 'Beneath a Steel Sky',
    fs_extension: '',
    fs_path: 'roms/scummvm',
    fs_size_bytes: 72564945,
    path_cover_small: '/assets/romm/resources/roms/10/139/cover/small.webp',
    path_cover_large: '/assets/romm/resources/roms/10/139/cover/big.png',
    url_cover: null,
    path_video: null,
    regions: [],
    languages: [],
    tags: [],
    revision: null,
    crc_hash: 'db8f95c2',
    md5_hash: 'cbac0fd783e10f980677039fb061787e',
    sha1_hash: '764a4dbd32cf005b3a44c35d310e4774f0084848',
    has_simple_single_file: false,
    has_nested_single_file: false,
    has_multiple_files: true,
    missing_from_fs: false,
    metadatum: {
      genres: ['Adventure', 'Indie', 'Point-and-click', 'Puzzle'],
      franchises: [],
      companies: [
        'Revolution Software',
        'Revolution Software',
        'Virgin Interactive Entertainment (Europe) Ltd.',
        'Virgin Interactive Entertainment, Inc.'
      ],
      game_modes: ['Single player'],
      age_ratings: ['12', 'T'],
      player_count: '1',
      first_release_date: 762480000,
      average_rating: 81.796666666
    },
    rom_user: {
      id: 139,
      rom_id: 139,
      last_played: null,
      now_playing: false,
      backlogged: false,
      hidden: false,
      rating: 0,
      difficulty: 0,
      completion: 0,
      status: null
    },
    files: [
      {
        id: 840,
        rom_id: 139,
        file_name: 'WRC-MANIFEST.JSON',
        file_path: 'roms/scummvm/Beneath a Steel Sky',
        file_size_bytes: 204,
        full_path: 'roms/scummvm/Beneath a Steel Sky/WRC-MANIFEST.JSON',
        category: 'game'
      },
      {
        id: 839,
        rom_id: 139,
        file_name: 'pak1.zip',
        file_path: 'roms/scummvm/Beneath a Steel Sky',
        file_size_bytes: 169028,
        full_path: 'roms/scummvm/Beneath a Steel Sky/pak1.zip',
        category: 'game'
      },
      {
        id: 841,
        rom_id: 139,
        file_name: 'sky.dsk',
        file_path: 'roms/scummvm/Beneath a Steel Sky',
        file_size_bytes: 72395713,
        full_path: 'roms/scummvm/Beneath a Steel Sky/sky.dsk',
        category: 'game'
      }
    ],
    merged_screenshots: [
      '/assets/romm/resources/roms/10/139/screenshots/0.jpg',
      '/assets/romm/resources/roms/10/139/screenshots/1.jpg'
    ],
    created_at: '2025-11-02T21:58:23+00:00',
    updated_at: '2026-07-05T12:21:16+00:00'
  },
  {
    id: 144,
    name: 'Lure of the Temptress',
    slug: 'lure-of-the-temptress',
    summary:
      'Lure of the Temptress is Revolution Softwares debut point-and-click adventure game published by Virgin Interactive Entertainment. It was released in June 1992 for Atari ST, MS-DOS and Amiga. The player assumes the role of a young peasant named Diermot who has to overthrow an evil sorceress. Lure of the Temptress is the first game built with the Virtual Theatre engine, which Revolution used in the subsequent games Beneath a Steel Sky and the first two games in the Broken Sword series. It was received favourably by critics, a commercial success and re-released as freeware on April 1, 2003.',
    platform_id: 10,
    platform_slug: 'scummvm',
    platform_fs_slug: 'scummvm',
    platform_display_name: 'ScummVM',
    fs_name: 'Lure of the Temptress',
    fs_name_no_ext: 'Lure of the Temptress',
    fs_name_no_tags: 'Lure of the Temptress',
    fs_extension: '',
    fs_path: 'roms/scummvm',
    fs_size_bytes: 3363387,
    path_cover_small: '/assets/romm/resources/roms/10/144/cover/small.webp',
    path_cover_large: '/assets/romm/resources/roms/10/144/cover/big.png',
    url_cover: null,
    path_video: null,
    regions: [],
    languages: [],
    tags: [],
    revision: null,
    crc_hash: '9b2ed166',
    md5_hash: '5e12d3bc0c0f96ec78a1db5f7da17eef',
    sha1_hash: '1001af2e462c5105c2b0e37a8e37b64893e6fe0d',
    has_simple_single_file: false,
    has_nested_single_file: true,
    has_multiple_files: false,
    missing_from_fs: false,
    metadatum: {
      genres: ['Adventure', 'Point-and-click', 'Puzzle'],
      franchises: [],
      companies: [
        'Konami',
        'Revolution Software',
        'Revolution Software',
        'Virgin Interactive Entertainment (Europe) Ltd.'
      ],
      game_modes: ['Single player'],
      age_ratings: ['6'],
      player_count: '1',
      first_release_date: 725760000,
      average_rating: 69.35
    },
    rom_user: {
      id: 144,
      rom_id: 144,
      last_played: null,
      now_playing: false,
      backlogged: false,
      hidden: false,
      rating: 0,
      difficulty: 0,
      completion: 0,
      status: null
    },
    files: [
      {
        id: 850,
        rom_id: 144,
        file_name: 'lure.zip',
        file_path: 'roms/scummvm/Lure of the Temptress',
        file_size_bytes: 3363387,
        full_path: 'roms/scummvm/Lure of the Temptress/lure.zip',
        category: 'game'
      }
    ],
    merged_screenshots: [
      '/assets/romm/resources/roms/10/144/screenshots/0.jpg',
      '/assets/romm/resources/roms/10/144/screenshots/1.jpg'
    ],
    created_at: '2025-11-02T21:58:27+00:00',
    updated_at: '2026-07-05T12:21:22+00:00'
  },
  {
    id: 149,
    name: 'Cimmerian',
    slug: null,
    summary:
      'A simplistic 1-on-1 sword fighting game produced for a homebrew competition in 2016. An homage to Barbarian on the C-64, and by extension very similar to Karate Champ or Budokan: The Martial Spirit. Slowly maneuver your clunky fighter towards the opponent, then press combinations of directions and buttons to unleash various moves. Features music ripped from the Game Gear version of WWF Raw. An updated version was said to be "nearly finished" in 2019, but never released.',
    platform_id: 11,
    platform_slug: 'sms',
    platform_fs_slug: 'sms',
    platform_display_name: 'Sega Master System/Mark III',
    fs_name: 'Cimmerian.sms',
    fs_name_no_ext: 'Cimmerian',
    fs_name_no_tags: 'Cimmerian',
    fs_extension: 'sms',
    fs_path: 'roms/sms',
    fs_size_bytes: 786432,
    path_cover_small: '/assets/romm/resources/roms/11/149/cover/small.webp',
    path_cover_large: '/assets/romm/resources/roms/11/149/cover/big.png',
    url_cover: null,
    path_video: null,
    regions: [],
    languages: [],
    tags: [],
    revision: null,
    crc_hash: '19923e38',
    md5_hash: 'c1a479065bc31e8681a8530118bdf1f7',
    sha1_hash: '654bdf3981d0ada7cbb20f74e72c79bad1089603',
    has_simple_single_file: true,
    has_nested_single_file: false,
    has_multiple_files: false,
    missing_from_fs: false,
    metadatum: {
      genres: ['Fighting'],
      franchises: [],
      companies: ['Ichigobankai'],
      game_modes: [],
      age_ratings: [],
      player_count: '1-2',
      first_release_date: 1459036800,
      average_rating: null
    },
    rom_user: {
      id: 149,
      rom_id: 149,
      last_played: null,
      now_playing: false,
      backlogged: false,
      hidden: false,
      rating: 0,
      difficulty: 0,
      completion: 0,
      status: null
    },
    files: [
      {
        id: 853,
        rom_id: 149,
        file_name: 'Cimmerian.sms',
        file_path: 'roms/sms',
        file_size_bytes: 786432,
        full_path: 'roms/sms/Cimmerian.sms',
        category: 'game'
      }
    ],
    merged_screenshots: [
      '/assets/romm/resources/roms/11/149/screenshots/0.jpg',
      '/assets/romm/resources/roms/11/149/screenshots/1.jpg'
    ],
    created_at: '2025-11-02T21:58:29+00:00',
    updated_at: '2026-07-05T12:21:34+00:00'
  },
  {
    id: 154,
    name: 'Galactic Revenge',
    slug: 'galactic-protector',
    summary:
      "It's the year 33XXX. Dirty aliens from a faraway galaxy emptied your refrigerator and killed your boyfriend. Confident in their superiority, they also had the nerve to steal your beloved Master System.\n\nNOW THEY'VE GONE TOO FAR...\n\nYou are Olivia Gun. Get your blastin' shoes on and pick from three killer outfits. Wield fire, spread shots, lasers, and even shurikens.\nWipe the grins off their faces as you jump, shoot, and fight your way through their ship and turn them into scrap as payback for their heinous deeds!",
    platform_id: 11,
    platform_slug: 'sms',
    platform_fs_slug: 'sms',
    platform_display_name: 'Sega Master System/Mark III',
    fs_name: 'galacticrevenge-v3.sms',
    fs_name_no_ext: 'galacticrevenge-v3',
    fs_name_no_tags: 'galacticrevenge-v3',
    fs_extension: 'sms',
    fs_path: 'roms/sms',
    fs_size_bytes: 131072,
    path_cover_small: '/assets/romm/resources/roms/11/154/cover/small.webp',
    path_cover_large: '/assets/romm/resources/roms/11/154/cover/big.png',
    url_cover: null,
    path_video: null,
    regions: [],
    languages: [],
    tags: [],
    revision: null,
    crc_hash: '4d69cd2c',
    md5_hash: '283812dcc11cc8b254d0a06ac6afd8fc',
    sha1_hash: 'c9a33510cc843499816061f453219b9eb93c6526',
    has_simple_single_file: true,
    has_nested_single_file: false,
    has_multiple_files: false,
    missing_from_fs: false,
    metadatum: {
      genres: ['Shooter'],
      franchises: [],
      companies: ['Sega Enterprises, Ltd.'],
      game_modes: ['Single player'],
      age_ratings: [],
      player_count: '1',
      first_release_date: 574905600,
      average_rating: 85.0
    },
    rom_user: {
      id: 154,
      rom_id: 154,
      last_played: null,
      now_playing: false,
      backlogged: false,
      hidden: false,
      rating: 0,
      difficulty: 0,
      completion: 0,
      status: null
    },
    files: [
      {
        id: 861,
        rom_id: 154,
        file_name: 'galacticrevenge-v3.sms',
        file_path: 'roms/sms',
        file_size_bytes: 131072,
        full_path: 'roms/sms/galacticrevenge-v3.sms',
        category: 'game'
      }
    ],
    merged_screenshots: [
      '/assets/romm/resources/roms/11/154/screenshots/0.jpg',
      '/assets/romm/resources/roms/11/154/screenshots/1.jpg'
    ],
    created_at: '2025-11-02T21:58:30+00:00',
    updated_at: '2026-07-05T12:21:45+00:00'
  },
  {
    id: 163,
    name: 'Super Boss Gaiden',
    slug: 'super-boss-gaiden',
    summary:
      "It is yet another lovely day of industry domination at Sony's HQ when top executives march into the titular Boss room to deliver some dire news: The very last SNES Playstation prototype has fallen in the hands of the public and homebrew enthusiasts have already managed to fully emulate the system. This represents a great shame for the Boss who had decades ago ordered the destruction of every single prototype. We have a feeling the Boss has not been paying attention to his yoga and meditation classes, because he promptly switches to rampage mode and proceeds to punch, kick and throw everything in Sony's headquarters, including employees and Sony mascots.",
    platform_id: 12,
    platform_slug: 'snes',
    platform_fs_slug: 'snes',
    platform_display_name: 'Super Nintendo Entertainment System',
    fs_name: 'Super Boss Gaiden (J) (V1.2).sfc',
    fs_name_no_ext: 'Super Boss Gaiden (J) (V1.2)',
    fs_name_no_tags: 'Super Boss Gaiden',
    fs_extension: 'sfc',
    fs_path: 'roms/snes',
    fs_size_bytes: 524288,
    path_cover_small: '/assets/romm/resources/roms/12/163/cover/small.webp',
    path_cover_large: '/assets/romm/resources/roms/12/163/cover/big.png',
    url_cover: null,
    path_video: null,
    regions: ['Japan'],
    languages: [],
    tags: ['V1.2'],
    revision: null,
    crc_hash: 'c9a8412d',
    md5_hash: '99a5ebfdf38faf4e194bfac535aa936b',
    sha1_hash: '60c61db61ea02c5ff4c57e72ec5147107628fe22',
    has_simple_single_file: true,
    has_nested_single_file: false,
    has_multiple_files: false,
    missing_from_fs: false,
    metadatum: {
      genres: ["Hack and slash/Beat 'em up", 'Platform'],
      franchises: [],
      companies: ['Chrono Moogle', 'Dieter Von Lazer (d4s)'],
      game_modes: ['Single player'],
      age_ratings: ['Not Rated'],
      player_count: '1',
      first_release_date: 1468108800,
      average_rating: 91.5
    },
    rom_user: {
      id: 163,
      rom_id: 163,
      last_played: null,
      now_playing: false,
      backlogged: false,
      hidden: false,
      rating: 0,
      difficulty: 0,
      completion: 0,
      status: null
    },
    files: [
      {
        id: 870,
        rom_id: 163,
        file_name: 'Super Boss Gaiden (J) (V1.2).sfc',
        file_path: 'roms/snes',
        file_size_bytes: 524288,
        full_path: 'roms/snes/Super Boss Gaiden (J) (V1.2).sfc',
        category: 'game'
      }
    ],
    merged_screenshots: [
      '/assets/romm/resources/roms/12/163/screenshots/0.jpg',
      '/assets/romm/resources/roms/12/163/screenshots/1.jpg'
    ],
    created_at: '2025-11-02T21:58:31+00:00',
    updated_at: '2026-07-05T12:22:13+00:00'
  },
  {
    id: 162,
    name: 'MazezaM Challenge',
    slug: 'mazezam-challenge',
    summary:
      'Mazezam Challenge is a Puzzle Video game. The main goal of the game is help the character pass through different stages that are filled with obstacles. The player has to be very careful while moving the obstacles to not close down his path, because if he does, he would need to restart the stage with the cost of a life. The game gives the option to write a password and advanced to the last stage you play. Mazezam has over 50 Stage levels and each level is harder than the last one. Mazezam was the winner of the Neo Flash 2012 video game competition and it was featured in a Retro Video Game Magazine from the UK. The game has both French and English text.',
    platform_id: 12,
    platform_slug: 'snes',
    platform_fs_slug: 'snes',
    platform_display_name: 'Super Nintendo Entertainment System',
    fs_name: 'MazezaM.sfc',
    fs_name_no_ext: 'MazezaM',
    fs_name_no_tags: 'MazezaM',
    fs_extension: 'sfc',
    fs_path: 'roms/snes',
    fs_size_bytes: 524288,
    path_cover_small: '/assets/romm/resources/roms/12/162/cover/small.webp',
    path_cover_large: '/assets/romm/resources/roms/12/162/cover/big.png',
    url_cover: null,
    path_video: null,
    regions: [],
    languages: [],
    tags: [],
    revision: null,
    crc_hash: '076ac3fe',
    md5_hash: 'dddaf6b133ef16c19a253b5465517513',
    sha1_hash: 'd263ffb10a1e4b8b177292fdb48973358a7c5aba',
    has_simple_single_file: true,
    has_nested_single_file: false,
    has_multiple_files: false,
    missing_from_fs: false,
    metadatum: {
      genres: ['Puzzle'],
      franchises: [],
      companies: ['Alekmaul', 'Piko Interactive'],
      game_modes: ['Single player'],
      age_ratings: ['Not Rated'],
      player_count: '1',
      first_release_date: 1388448000,
      average_rating: 66.0
    },
    rom_user: {
      id: 162,
      rom_id: 162,
      last_played: null,
      now_playing: false,
      backlogged: false,
      hidden: false,
      rating: 0,
      difficulty: 0,
      completion: 0,
      status: null
    },
    files: [
      {
        id: 866,
        rom_id: 162,
        file_name: 'MazezaM.sfc',
        file_path: 'roms/snes',
        file_size_bytes: 524288,
        full_path: 'roms/snes/MazezaM.sfc',
        category: 'game'
      }
    ],
    merged_screenshots: [
      '/assets/romm/resources/roms/12/162/screenshots/0.jpg',
      '/assets/romm/resources/roms/12/162/screenshots/1.jpg'
    ],
    created_at: '2025-11-02T21:58:31+00:00',
    updated_at: '2026-07-05T12:22:06+00:00'
  }
]
